name: deeplab

channels:
- conda-forge
- pytorch
- nvidia

dependencies:
- matplotlib
- python=3.10
- setuptools
- numpy
- scikit-learn
- time
- scikit-image
- pandas
- tensorflow
- keras
- jupyter
- notebook
- jupyterlab
- pytorch 
- horovod
- dask
- pip
- pip:
  - opencv-python-headless
  - pathlib

